/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssignRoleToUserRequest
 */
export interface AssignRoleToUserRequest {
    /**
     * User identifier
     * @type {string}
     * @memberof AssignRoleToUserRequest
     */
    userId: string;
    /**
     * Role identifier
     * @type {string}
     * @memberof AssignRoleToUserRequest
     */
    roleId: string;
}

/**
 * Check if a given object implements the AssignRoleToUserRequest interface.
 */
export function instanceOfAssignRoleToUserRequest(value: object): value is AssignRoleToUserRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    return true;
}

export function AssignRoleToUserRequestFromJSON(json: any): AssignRoleToUserRequest {
    return AssignRoleToUserRequestFromJSONTyped(json, false);
}

export function AssignRoleToUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignRoleToUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'roleId': json['roleId'],
    };
}

  export function AssignRoleToUserRequestToJSON(json: any): AssignRoleToUserRequest {
      return AssignRoleToUserRequestToJSONTyped(json, false);
  }

  export function AssignRoleToUserRequestToJSONTyped(value?: AssignRoleToUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'roleId': value['roleId'],
    };
}

