/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkerRequest
 */
export interface CreateWorkerRequest {
    /**
     * Name of the worker
     * @type {string}
     * @memberof CreateWorkerRequest
     */
    name: string | null;
    /**
     * Speciality of the worker
     * @type {string}
     * @memberof CreateWorkerRequest
     */
    speciality: string | null;
    /**
     * Contact of the worker
     * @type {string}
     * @memberof CreateWorkerRequest
     */
    contact: string | null;
    /**
     * Email of the worker
     * @type {string}
     * @memberof CreateWorkerRequest
     */
    address: string | null;
    /**
     * Phone of the worker
     * @type {string}
     * @memberof CreateWorkerRequest
     */
    phone: string | null;
    /**
     * City of the worker
     * @type {string}
     * @memberof CreateWorkerRequest
     */
    socialSecurity: string | null;
    /**
     * State of the worker
     * @type {string}
     * @memberof CreateWorkerRequest
     */
    startDate: string | null;
    /**
     * Zip of the worker
     * @type {string}
     * @memberof CreateWorkerRequest
     */
    endDate: string | null;
}

/**
 * Check if a given object implements the CreateWorkerRequest interface.
 */
export function instanceOfCreateWorkerRequest(value: object): value is CreateWorkerRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('speciality' in value) || value['speciality'] === undefined) return false;
    if (!('contact' in value) || value['contact'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('socialSecurity' in value) || value['socialSecurity'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    return true;
}

export function CreateWorkerRequestFromJSON(json: any): CreateWorkerRequest {
    return CreateWorkerRequestFromJSONTyped(json, false);
}

export function CreateWorkerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'speciality': json['speciality'],
        'contact': json['contact'],
        'address': json['address'],
        'phone': json['phone'],
        'socialSecurity': json['socialSecurity'],
        'startDate': json['startDate'],
        'endDate': json['endDate'],
    };
}

  export function CreateWorkerRequestToJSON(json: any): CreateWorkerRequest {
      return CreateWorkerRequestToJSONTyped(json, false);
  }

  export function CreateWorkerRequestToJSONTyped(value?: CreateWorkerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'speciality': value['speciality'],
        'contact': value['contact'],
        'address': value['address'],
        'phone': value['phone'],
        'socialSecurity': value['socialSecurity'],
        'startDate': value['startDate'],
        'endDate': value['endDate'],
    };
}

