/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMaterialRequest
 */
export interface CreateMaterialRequest {
    /**
     * Name of the material
     * @type {string}
     * @memberof CreateMaterialRequest
     */
    name: string | null;
    /**
     * Unit cost of the material
     * @type {number}
     * @memberof CreateMaterialRequest
     */
    unitCost: number | null;
}

/**
 * Check if a given object implements the CreateMaterialRequest interface.
 */
export function instanceOfCreateMaterialRequest(value: object): value is CreateMaterialRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('unitCost' in value) || value['unitCost'] === undefined) return false;
    return true;
}

export function CreateMaterialRequestFromJSON(json: any): CreateMaterialRequest {
    return CreateMaterialRequestFromJSONTyped(json, false);
}

export function CreateMaterialRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMaterialRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'unitCost': json['unitCost'],
    };
}

  export function CreateMaterialRequestToJSON(json: any): CreateMaterialRequest {
      return CreateMaterialRequestToJSONTyped(json, false);
  }

  export function CreateMaterialRequestToJSONTyped(value?: CreateMaterialRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'unitCost': value['unitCost'],
    };
}

