/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateServiceRequest
 */
export interface CreateServiceRequest {
    /**
     * Name of the service
     * @type {string}
     * @memberof CreateServiceRequest
     */
    name: string | null;
    /**
     * Description of the service
     * @type {string}
     * @memberof CreateServiceRequest
     */
    description: string | null;
    /**
     * Project ID of the service
     * @type {string}
     * @memberof CreateServiceRequest
     */
    unitCost: string | null;
}

/**
 * Check if a given object implements the CreateServiceRequest interface.
 */
export function instanceOfCreateServiceRequest(value: object): value is CreateServiceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('unitCost' in value) || value['unitCost'] === undefined) return false;
    return true;
}

export function CreateServiceRequestFromJSON(json: any): CreateServiceRequest {
    return CreateServiceRequestFromJSONTyped(json, false);
}

export function CreateServiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateServiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'unitCost': json['unitCost'],
    };
}

  export function CreateServiceRequestToJSON(json: any): CreateServiceRequest {
      return CreateServiceRequestToJSONTyped(json, false);
  }

  export function CreateServiceRequestToJSONTyped(value?: CreateServiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'unitCost': value['unitCost'],
    };
}

