/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProjectRequest
 */
export interface CreateProjectRequest {
    /**
     * Client id of the project
     * @type {string}
     * @memberof CreateProjectRequest
     */
    clientId: string | null;
    /**
     * Name of the project
     * @type {string}
     * @memberof CreateProjectRequest
     */
    name: string | null;
    /**
     * Description of the project
     * @type {string}
     * @memberof CreateProjectRequest
     */
    description: string | null;
    /**
     * Location of the project
     * @type {string}
     * @memberof CreateProjectRequest
     */
    location: string | null;
    /**
     * Start date of the project
     * @type {string}
     * @memberof CreateProjectRequest
     */
    startDate: string | null;
    /**
     * End date of the project
     * @type {string}
     * @memberof CreateProjectRequest
     */
    endDate: string | null;
}

/**
 * Check if a given object implements the CreateProjectRequest interface.
 */
export function instanceOfCreateProjectRequest(value: object): value is CreateProjectRequest {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    return true;
}

export function CreateProjectRequestFromJSON(json: any): CreateProjectRequest {
    return CreateProjectRequestFromJSONTyped(json, false);
}

export function CreateProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['clientId'],
        'name': json['name'],
        'description': json['description'],
        'location': json['location'],
        'startDate': json['startDate'],
        'endDate': json['endDate'],
    };
}

  export function CreateProjectRequestToJSON(json: any): CreateProjectRequest {
      return CreateProjectRequestToJSONTyped(json, false);
  }

  export function CreateProjectRequestToJSONTyped(value?: CreateProjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientId': value['clientId'],
        'name': value['name'],
        'description': value['description'],
        'location': value['location'],
        'startDate': value['startDate'],
        'endDate': value['endDate'],
    };
}

