/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkerRatesRequest
 */
export interface CreateWorkerRatesRequest {
    /**
     * Rate of the workerRates
     * @type {number}
     * @memberof CreateWorkerRatesRequest
     */
    rate: number | null;
    /**
     * Effective date of the workerRates
     * @type {Date}
     * @memberof CreateWorkerRatesRequest
     */
    effectiveDate: Date | null;
}

/**
 * Check if a given object implements the CreateWorkerRatesRequest interface.
 */
export function instanceOfCreateWorkerRatesRequest(value: object): value is CreateWorkerRatesRequest {
    if (!('rate' in value) || value['rate'] === undefined) return false;
    if (!('effectiveDate' in value) || value['effectiveDate'] === undefined) return false;
    return true;
}

export function CreateWorkerRatesRequestFromJSON(json: any): CreateWorkerRatesRequest {
    return CreateWorkerRatesRequestFromJSONTyped(json, false);
}

export function CreateWorkerRatesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkerRatesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rate': json['rate'],
        'effectiveDate': (json['effectiveDate'] == null ? null : new Date(json['effectiveDate'])),
    };
}

  export function CreateWorkerRatesRequestToJSON(json: any): CreateWorkerRatesRequest {
      return CreateWorkerRatesRequestToJSONTyped(json, false);
  }

  export function CreateWorkerRatesRequestToJSONTyped(value?: CreateWorkerRatesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rate': value['rate'],
        'effectiveDate': (value['effectiveDate'] == null ? null : (value['effectiveDate'] as any).toISOString()),
    };
}

