/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateServiceSheetsRequest
 */
export interface CreateServiceSheetsRequest {
    /**
     * Name of the serviceSheets
     * @type {string}
     * @memberof CreateServiceSheetsRequest
     */
    workerId: string | null;
    /**
     * Speciality of the serviceSheets
     * @type {string}
     * @memberof CreateServiceSheetsRequest
     */
    projectId: string | null;
    /**
     * Contact of the serviceSheets
     * @type {string}
     * @memberof CreateServiceSheetsRequest
     */
    weekStartDate: string | null;
    /**
     * Email of the serviceSheets
     * @type {number}
     * @memberof CreateServiceSheetsRequest
     */
    totalHours: number | null;
}

/**
 * Check if a given object implements the CreateServiceSheetsRequest interface.
 */
export function instanceOfCreateServiceSheetsRequest(value: object): value is CreateServiceSheetsRequest {
    if (!('workerId' in value) || value['workerId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('weekStartDate' in value) || value['weekStartDate'] === undefined) return false;
    if (!('totalHours' in value) || value['totalHours'] === undefined) return false;
    return true;
}

export function CreateServiceSheetsRequestFromJSON(json: any): CreateServiceSheetsRequest {
    return CreateServiceSheetsRequestFromJSONTyped(json, false);
}

export function CreateServiceSheetsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateServiceSheetsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'workerId': json['workerId'],
        'projectId': json['projectId'],
        'weekStartDate': json['weekStartDate'],
        'totalHours': json['totalHours'],
    };
}

  export function CreateServiceSheetsRequestToJSON(json: any): CreateServiceSheetsRequest {
      return CreateServiceSheetsRequestToJSONTyped(json, false);
  }

  export function CreateServiceSheetsRequestToJSONTyped(value?: CreateServiceSheetsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workerId': value['workerId'],
        'projectId': value['projectId'],
        'weekStartDate': value['weekStartDate'],
        'totalHours': value['totalHours'],
    };
}

