/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoicesResponse
 */
export interface InvoicesResponse {
    /**
     * Id of the invoices
     * @type {string}
     * @memberof InvoicesResponse
     */
    id: string;
    /**
     * Stage id of invoices
     * @type {string}
     * @memberof InvoicesResponse
     */
    stageId: string | null;
    /**
     * Invoice number of invoices
     * @type {string}
     * @memberof InvoicesResponse
     */
    invoiceNumber: string | null;
    /**
     * Date of invoices
     * @type {string}
     * @memberof InvoicesResponse
     */
    date: string | null;
    /**
     * Total amount of invoices
     * @type {number}
     * @memberof InvoicesResponse
     */
    totalAmount: number | null;
    /**
     * Show materials of invoices
     * @type {boolean}
     * @memberof InvoicesResponse
     */
    showMaterials: boolean | null;
    /**
     * Created at of the invoices
     * @type {string}
     * @memberof InvoicesResponse
     */
    createdAt: string | null;
    /**
     * Updated at of the invoices
     * @type {string}
     * @memberof InvoicesResponse
     */
    updatedAt: string | null;
}

/**
 * Check if a given object implements the InvoicesResponse interface.
 */
export function instanceOfInvoicesResponse(value: object): value is InvoicesResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('stageId' in value) || value['stageId'] === undefined) return false;
    if (!('invoiceNumber' in value) || value['invoiceNumber'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('totalAmount' in value) || value['totalAmount'] === undefined) return false;
    if (!('showMaterials' in value) || value['showMaterials'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function InvoicesResponseFromJSON(json: any): InvoicesResponse {
    return InvoicesResponseFromJSONTyped(json, false);
}

export function InvoicesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoicesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'stageId': json['stageId'],
        'invoiceNumber': json['invoiceNumber'],
        'date': json['date'],
        'totalAmount': json['totalAmount'],
        'showMaterials': json['showMaterials'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

  export function InvoicesResponseToJSON(json: any): InvoicesResponse {
      return InvoicesResponseToJSONTyped(json, false);
  }

  export function InvoicesResponseToJSONTyped(value?: InvoicesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'stageId': value['stageId'],
        'invoiceNumber': value['invoiceNumber'],
        'date': value['date'],
        'totalAmount': value['totalAmount'],
        'showMaterials': value['showMaterials'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

