/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';

/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * User data
     * @type {UserResponse}
     * @memberof LoginResponse
     */
    user: UserResponse;
    /**
     * Roles of the user
     * @type {Array<string>}
     * @memberof LoginResponse
     */
    roles: Array<string>;
    /**
     * Access token of the user
     * @type {string}
     * @memberof LoginResponse
     */
    accessToken: string;
    /**
     * Refresh token of the user
     * @type {string}
     * @memberof LoginResponse
     */
    refreshToken: string;
    /**
     * Access token expiration time
     * @type {number}
     * @memberof LoginResponse
     */
    accessTokenExpiresIn: number;
    /**
     * Refresh token expiration time
     * @type {number}
     * @memberof LoginResponse
     */
    refreshTokenExpiresIn: number;
    /**
     * Access token expiration date
     * @type {Date}
     * @memberof LoginResponse
     */
    accessTokenExpiresAt: Date;
    /**
     * Refresh token expiration date
     * @type {Date}
     * @memberof LoginResponse
     */
    refreshTokenExpiresAt: Date;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('accessTokenExpiresIn' in value) || value['accessTokenExpiresIn'] === undefined) return false;
    if (!('refreshTokenExpiresIn' in value) || value['refreshTokenExpiresIn'] === undefined) return false;
    if (!('accessTokenExpiresAt' in value) || value['accessTokenExpiresAt'] === undefined) return false;
    if (!('refreshTokenExpiresAt' in value) || value['refreshTokenExpiresAt'] === undefined) return false;
    return true;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
    return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserResponseFromJSON(json['user']),
        'roles': json['roles'],
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
        'accessTokenExpiresIn': json['accessTokenExpiresIn'],
        'refreshTokenExpiresIn': json['refreshTokenExpiresIn'],
        'accessTokenExpiresAt': (new Date(json['accessTokenExpiresAt'])),
        'refreshTokenExpiresAt': (new Date(json['refreshTokenExpiresAt'])),
    };
}

  export function LoginResponseToJSON(json: any): LoginResponse {
      return LoginResponseToJSONTyped(json, false);
  }

  export function LoginResponseToJSONTyped(value?: LoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserResponseToJSON(value['user']),
        'roles': value['roles'],
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
        'accessTokenExpiresIn': value['accessTokenExpiresIn'],
        'refreshTokenExpiresIn': value['refreshTokenExpiresIn'],
        'accessTokenExpiresAt': ((value['accessTokenExpiresAt']).toISOString()),
        'refreshTokenExpiresAt': ((value['refreshTokenExpiresAt']).toISOString()),
    };
}

