/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaterialResponse } from './MaterialResponse';
import {
    MaterialResponseFromJSON,
    MaterialResponseFromJSONTyped,
    MaterialResponseToJSON,
    MaterialResponseToJSONTyped,
} from './MaterialResponse';

/**
 * 
 * @export
 * @interface MaterialPaginationResponse
 */
export interface MaterialPaginationResponse {
    /**
     * Data of the material
     * @type {Array<MaterialResponse>}
     * @memberof MaterialPaginationResponse
     */
    data: Array<MaterialResponse>;
    /**
     * Total of the material
     * @type {number}
     * @memberof MaterialPaginationResponse
     */
    total: number;
}

/**
 * Check if a given object implements the MaterialPaginationResponse interface.
 */
export function instanceOfMaterialPaginationResponse(value: object): value is MaterialPaginationResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function MaterialPaginationResponseFromJSON(json: any): MaterialPaginationResponse {
    return MaterialPaginationResponseFromJSONTyped(json, false);
}

export function MaterialPaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaterialPaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(MaterialResponseFromJSON)),
        'total': json['total'],
    };
}

  export function MaterialPaginationResponseToJSON(json: any): MaterialPaginationResponse {
      return MaterialPaginationResponseToJSONTyped(json, false);
  }

  export function MaterialPaginationResponseToJSONTyped(value?: MaterialPaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(MaterialResponseToJSON)),
        'total': value['total'],
    };
}

