/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationsResponse } from './NotificationsResponse';
import {
    NotificationsResponseFromJSON,
    NotificationsResponseFromJSONTyped,
    NotificationsResponseToJSON,
    NotificationsResponseToJSONTyped,
} from './NotificationsResponse';

/**
 * 
 * @export
 * @interface NotificationsPaginationResponse
 */
export interface NotificationsPaginationResponse {
    /**
     * Data of the notifications
     * @type {Array<NotificationsResponse>}
     * @memberof NotificationsPaginationResponse
     */
    data: Array<NotificationsResponse>;
    /**
     * Total of the notifications
     * @type {number}
     * @memberof NotificationsPaginationResponse
     */
    total: number;
}

/**
 * Check if a given object implements the NotificationsPaginationResponse interface.
 */
export function instanceOfNotificationsPaginationResponse(value: object): value is NotificationsPaginationResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function NotificationsPaginationResponseFromJSON(json: any): NotificationsPaginationResponse {
    return NotificationsPaginationResponseFromJSONTyped(json, false);
}

export function NotificationsPaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationsPaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(NotificationsResponseFromJSON)),
        'total': json['total'],
    };
}

  export function NotificationsPaginationResponseToJSON(json: any): NotificationsPaginationResponse {
      return NotificationsPaginationResponseToJSONTyped(json, false);
  }

  export function NotificationsPaginationResponseToJSONTyped(value?: NotificationsPaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(NotificationsResponseToJSON)),
        'total': value['total'],
    };
}

