/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectResponse
 */
export interface ProjectResponse {
    /**
     * Name of the project
     * @type {string}
     * @memberof ProjectResponse
     */
    name: string | null;
    /**
     * Description of the project
     * @type {string}
     * @memberof ProjectResponse
     */
    description: string | null;
    /**
     * Client id of the project
     * @type {string}
     * @memberof ProjectResponse
     */
    clientId: string | null;
    /**
     * Location of the project
     * @type {string}
     * @memberof ProjectResponse
     */
    location: string | null;
    /**
     * Start date of the project
     * @type {Date}
     * @memberof ProjectResponse
     */
    startDate: Date | null;
    /**
     * End date of the project
     * @type {Date}
     * @memberof ProjectResponse
     */
    endDate: Date | null;
    /**
     * Id of the project
     * @type {string}
     * @memberof ProjectResponse
     */
    id: string;
    /**
     * Created at of the project
     * @type {Date}
     * @memberof ProjectResponse
     */
    createdAt: Date | null;
    /**
     * Updated at of the project
     * @type {Date}
     * @memberof ProjectResponse
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the ProjectResponse interface.
 */
export function instanceOfProjectResponse(value: object): value is ProjectResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProjectResponseFromJSON(json: any): ProjectResponse {
    return ProjectResponseFromJSONTyped(json, false);
}

export function ProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'clientId': json['clientId'],
        'location': json['location'],
        'startDate': (json['startDate'] == null ? null : new Date(json['startDate'])),
        'endDate': (json['endDate'] == null ? null : new Date(json['endDate'])),
        'id': json['id'],
        'createdAt': (json['createdAt'] == null ? null : new Date(json['createdAt'])),
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
    };
}

  export function ProjectResponseToJSON(json: any): ProjectResponse {
      return ProjectResponseToJSONTyped(json, false);
  }

  export function ProjectResponseToJSONTyped(value?: ProjectResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'clientId': value['clientId'],
        'location': value['location'],
        'startDate': (value['startDate'] == null ? null : (value['startDate'] as any).toISOString()),
        'endDate': (value['endDate'] == null ? null : (value['endDate'] as any).toISOString()),
        'id': value['id'],
        'createdAt': (value['createdAt'] == null ? null : (value['createdAt'] as any).toISOString()),
        'updatedAt': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
    };
}

