/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectResponse } from './ProjectResponse';
import {
    ProjectResponseFromJSON,
    ProjectResponseFromJSONTyped,
    ProjectResponseToJSON,
    ProjectResponseToJSONTyped,
} from './ProjectResponse';

/**
 * 
 * @export
 * @interface ProjectPaginationResponse
 */
export interface ProjectPaginationResponse {
    /**
     * Data of the project
     * @type {Array<ProjectResponse>}
     * @memberof ProjectPaginationResponse
     */
    data: Array<ProjectResponse>;
    /**
     * Total of the project
     * @type {number}
     * @memberof ProjectPaginationResponse
     */
    total: number;
}

/**
 * Check if a given object implements the ProjectPaginationResponse interface.
 */
export function instanceOfProjectPaginationResponse(value: object): value is ProjectPaginationResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ProjectPaginationResponseFromJSON(json: any): ProjectPaginationResponse {
    return ProjectPaginationResponseFromJSONTyped(json, false);
}

export function ProjectPaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectPaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ProjectResponseFromJSON)),
        'total': json['total'],
    };
}

  export function ProjectPaginationResponseToJSON(json: any): ProjectPaginationResponse {
      return ProjectPaginationResponseToJSONTyped(json, false);
  }

  export function ProjectPaginationResponseToJSONTyped(value?: ProjectPaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ProjectResponseToJSON)),
        'total': value['total'],
    };
}

