/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectQuotationResponse
 */
export interface ProjectQuotationResponse {
    /**
     * Name of the projectQuotation
     * @type {string}
     * @memberof ProjectQuotationResponse
     */
    projectId: string | null;
    /**
     * Material ID of the projectQuotation
     * @type {string}
     * @memberof ProjectQuotationResponse
     */
    materialId: string | null;
    /**
     * Service ID of the projectQuotation
     * @type {string}
     * @memberof ProjectQuotationResponse
     */
    serviceId: string | null;
    /**
     * Quantity of the projectQuotation
     * @type {number}
     * @memberof ProjectQuotationResponse
     */
    quantity: number | null;
    /**
     * Total cost of the projectQuotation
     * @type {number}
     * @memberof ProjectQuotationResponse
     */
    totalCost: number | null;
    /**
     * ID of the projectQuotation
     * @type {string}
     * @memberof ProjectQuotationResponse
     */
    id: string;
    /**
     * Created at of the projectQuotation
     * @type {Date}
     * @memberof ProjectQuotationResponse
     */
    createdAt: Date | null;
    /**
     * Updated at of the projectQuotation
     * @type {Date}
     * @memberof ProjectQuotationResponse
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the ProjectQuotationResponse interface.
 */
export function instanceOfProjectQuotationResponse(value: object): value is ProjectQuotationResponse {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('materialId' in value) || value['materialId'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('totalCost' in value) || value['totalCost'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProjectQuotationResponseFromJSON(json: any): ProjectQuotationResponse {
    return ProjectQuotationResponseFromJSONTyped(json, false);
}

export function ProjectQuotationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectQuotationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'],
        'materialId': json['materialId'],
        'serviceId': json['serviceId'],
        'quantity': json['quantity'],
        'totalCost': json['totalCost'],
        'id': json['id'],
        'createdAt': (json['createdAt'] == null ? null : new Date(json['createdAt'])),
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
    };
}

  export function ProjectQuotationResponseToJSON(json: any): ProjectQuotationResponse {
      return ProjectQuotationResponseToJSONTyped(json, false);
  }

  export function ProjectQuotationResponseToJSONTyped(value?: ProjectQuotationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
        'materialId': value['materialId'],
        'serviceId': value['serviceId'],
        'quantity': value['quantity'],
        'totalCost': value['totalCost'],
        'id': value['id'],
        'createdAt': (value['createdAt'] == null ? null : (value['createdAt'] as any).toISOString()),
        'updatedAt': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
    };
}

