/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoveRoleFromUserRequest
 */
export interface RemoveRoleFromUserRequest {
    /**
     * User identifier
     * @type {string}
     * @memberof RemoveRoleFromUserRequest
     */
    userId: string;
    /**
     * Role identifier
     * @type {string}
     * @memberof RemoveRoleFromUserRequest
     */
    roleId: string;
}

/**
 * Check if a given object implements the RemoveRoleFromUserRequest interface.
 */
export function instanceOfRemoveRoleFromUserRequest(value: object): value is RemoveRoleFromUserRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    return true;
}

export function RemoveRoleFromUserRequestFromJSON(json: any): RemoveRoleFromUserRequest {
    return RemoveRoleFromUserRequestFromJSONTyped(json, false);
}

export function RemoveRoleFromUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveRoleFromUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'roleId': json['roleId'],
    };
}

  export function RemoveRoleFromUserRequestToJSON(json: any): RemoveRoleFromUserRequest {
      return RemoveRoleFromUserRequestToJSONTyped(json, false);
  }

  export function RemoveRoleFromUserRequestToJSONTyped(value?: RemoveRoleFromUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'roleId': value['roleId'],
    };
}

