/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceSheetsResponse } from './ServiceSheetsResponse';
import {
    ServiceSheetsResponseFromJSON,
    ServiceSheetsResponseFromJSONTyped,
    ServiceSheetsResponseToJSON,
    ServiceSheetsResponseToJSONTyped,
} from './ServiceSheetsResponse';

/**
 * 
 * @export
 * @interface ServiceSheetsPaginationResponse
 */
export interface ServiceSheetsPaginationResponse {
    /**
     * Data of the serviceSheets
     * @type {Array<ServiceSheetsResponse>}
     * @memberof ServiceSheetsPaginationResponse
     */
    data: Array<ServiceSheetsResponse>;
    /**
     * Total of the serviceSheets
     * @type {number}
     * @memberof ServiceSheetsPaginationResponse
     */
    total: number;
}

/**
 * Check if a given object implements the ServiceSheetsPaginationResponse interface.
 */
export function instanceOfServiceSheetsPaginationResponse(value: object): value is ServiceSheetsPaginationResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ServiceSheetsPaginationResponseFromJSON(json: any): ServiceSheetsPaginationResponse {
    return ServiceSheetsPaginationResponseFromJSONTyped(json, false);
}

export function ServiceSheetsPaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceSheetsPaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ServiceSheetsResponseFromJSON)),
        'total': json['total'],
    };
}

  export function ServiceSheetsPaginationResponseToJSON(json: any): ServiceSheetsPaginationResponse {
      return ServiceSheetsPaginationResponseToJSONTyped(json, false);
  }

  export function ServiceSheetsPaginationResponseToJSONTyped(value?: ServiceSheetsPaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ServiceSheetsResponseToJSON)),
        'total': value['total'],
    };
}

