/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceResponse } from './ServiceResponse';
import {
    ServiceResponseFromJSON,
    ServiceResponseFromJSONTyped,
    ServiceResponseToJSON,
    ServiceResponseToJSONTyped,
} from './ServiceResponse';

/**
 * 
 * @export
 * @interface ServicePaginationResponse
 */
export interface ServicePaginationResponse {
    /**
     * Data of the service
     * @type {Array<ServiceResponse>}
     * @memberof ServicePaginationResponse
     */
    data: Array<ServiceResponse>;
    /**
     * Total of the service
     * @type {number}
     * @memberof ServicePaginationResponse
     */
    total: number;
}

/**
 * Check if a given object implements the ServicePaginationResponse interface.
 */
export function instanceOfServicePaginationResponse(value: object): value is ServicePaginationResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ServicePaginationResponseFromJSON(json: any): ServicePaginationResponse {
    return ServicePaginationResponseFromJSONTyped(json, false);
}

export function ServicePaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicePaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ServiceResponseFromJSON)),
        'total': json['total'],
    };
}

  export function ServicePaginationResponseToJSON(json: any): ServicePaginationResponse {
      return ServicePaginationResponseToJSONTyped(json, false);
  }

  export function ServicePaginationResponseToJSONTyped(value?: ServicePaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ServiceResponseToJSON)),
        'total': value['total'],
    };
}

