/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceSheetsResponse
 */
export interface ServiceSheetsResponse {
    /**
     * Id of the serviceSheets
     * @type {string}
     * @memberof ServiceSheetsResponse
     */
    id: string;
    /**
     * Name of the serviceSheets
     * @type {string}
     * @memberof ServiceSheetsResponse
     */
    workerId: string | null;
    /**
     * Speciality of the serviceSheets
     * @type {string}
     * @memberof ServiceSheetsResponse
     */
    projectId: string | null;
    /**
     * Contact of the serviceSheets
     * @type {string}
     * @memberof ServiceSheetsResponse
     */
    weekStartDate: string | null;
    /**
     * Email of the serviceSheets
     * @type {string}
     * @memberof ServiceSheetsResponse
     */
    totalHours: string | null;
    /**
     * Created at of the serviceSheets
     * @type {string}
     * @memberof ServiceSheetsResponse
     */
    createdAt: string | null;
    /**
     * Updated at of the serviceSheets
     * @type {string}
     * @memberof ServiceSheetsResponse
     */
    updatedAt: string | null;
}

/**
 * Check if a given object implements the ServiceSheetsResponse interface.
 */
export function instanceOfServiceSheetsResponse(value: object): value is ServiceSheetsResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('workerId' in value) || value['workerId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('weekStartDate' in value) || value['weekStartDate'] === undefined) return false;
    if (!('totalHours' in value) || value['totalHours'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ServiceSheetsResponseFromJSON(json: any): ServiceSheetsResponse {
    return ServiceSheetsResponseFromJSONTyped(json, false);
}

export function ServiceSheetsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceSheetsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'workerId': json['workerId'],
        'projectId': json['projectId'],
        'weekStartDate': json['weekStartDate'],
        'totalHours': json['totalHours'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

  export function ServiceSheetsResponseToJSON(json: any): ServiceSheetsResponse {
      return ServiceSheetsResponseToJSONTyped(json, false);
  }

  export function ServiceSheetsResponseToJSONTyped(value?: ServiceSheetsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workerId': value['workerId'],
        'projectId': value['projectId'],
        'weekStartDate': value['weekStartDate'],
        'totalHours': value['totalHours'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

