/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceResponse
 */
export interface ServiceResponse {
    /**
     * Id of the service
     * @type {string}
     * @memberof ServiceResponse
     */
    id: string;
    /**
     * Name of the service
     * @type {string}
     * @memberof ServiceResponse
     */
    name: string | null;
    /**
     * Description of the service
     * @type {string}
     * @memberof ServiceResponse
     */
    description: string | null;
    /**
     * Project ID of the service
     * @type {string}
     * @memberof ServiceResponse
     */
    unitCost: string | null;
    /**
     * Created at of the service
     * @type {string}
     * @memberof ServiceResponse
     */
    createdAt: string | null;
    /**
     * Updated at of the service
     * @type {string}
     * @memberof ServiceResponse
     */
    updatedAt: string | null;
}

/**
 * Check if a given object implements the ServiceResponse interface.
 */
export function instanceOfServiceResponse(value: object): value is ServiceResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('unitCost' in value) || value['unitCost'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ServiceResponseFromJSON(json: any): ServiceResponse {
    return ServiceResponseFromJSONTyped(json, false);
}

export function ServiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'unitCost': json['unitCost'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

  export function ServiceResponseToJSON(json: any): ServiceResponse {
      return ServiceResponseToJSONTyped(json, false);
  }

  export function ServiceResponseToJSONTyped(value?: ServiceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'unitCost': value['unitCost'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

