/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StageResponse
 */
export interface StageResponse {
    /**
     * Id of the stage
     * @type {string}
     * @memberof StageResponse
     */
    id: string;
    /**
     * Name of the stage
     * @type {string}
     * @memberof StageResponse
     */
    name: string | null;
    /**
     * Description of the stage
     * @type {string}
     * @memberof StageResponse
     */
    description: string | null;
    /**
     * Project ID of the stage
     * @type {string}
     * @memberof StageResponse
     */
    projectId: string | null;
    /**
     * Percentage of the stage
     * @type {number}
     * @memberof StageResponse
     */
    percentage: number | null;
    /**
     * Adjusted percentage of the stage
     * @type {number}
     * @memberof StageResponse
     */
    adjustedPercentage: number | null;
    /**
     * Start date of the stage
     * @type {Date}
     * @memberof StageResponse
     */
    startDate: Date | null;
    /**
     * End date of the stage
     * @type {Date}
     * @memberof StageResponse
     */
    endDate: Date | null;
    /**
     * Created at of the stage
     * @type {string}
     * @memberof StageResponse
     */
    createdAt: string | null;
    /**
     * Updated at of the stage
     * @type {string}
     * @memberof StageResponse
     */
    updatedAt: string | null;
}

/**
 * Check if a given object implements the StageResponse interface.
 */
export function instanceOfStageResponse(value: object): value is StageResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('percentage' in value) || value['percentage'] === undefined) return false;
    if (!('adjustedPercentage' in value) || value['adjustedPercentage'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function StageResponseFromJSON(json: any): StageResponse {
    return StageResponseFromJSONTyped(json, false);
}

export function StageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'projectId': json['projectId'],
        'percentage': json['percentage'],
        'adjustedPercentage': json['adjustedPercentage'],
        'startDate': (json['startDate'] == null ? null : new Date(json['startDate'])),
        'endDate': (json['endDate'] == null ? null : new Date(json['endDate'])),
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

  export function StageResponseToJSON(json: any): StageResponse {
      return StageResponseToJSONTyped(json, false);
  }

  export function StageResponseToJSONTyped(value?: StageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'projectId': value['projectId'],
        'percentage': value['percentage'],
        'adjustedPercentage': value['adjustedPercentage'],
        'startDate': (value['startDate'] == null ? null : (value['startDate'] as any).toISOString()),
        'endDate': (value['endDate'] == null ? null : (value['endDate'] as any).toISOString()),
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

