/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StageResponse } from './StageResponse';
import {
    StageResponseFromJSON,
    StageResponseFromJSONTyped,
    StageResponseToJSON,
    StageResponseToJSONTyped,
} from './StageResponse';

/**
 * 
 * @export
 * @interface StagePaginationResponse
 */
export interface StagePaginationResponse {
    /**
     * Data of the stage
     * @type {Array<StageResponse>}
     * @memberof StagePaginationResponse
     */
    data: Array<StageResponse>;
    /**
     * Total of the stage
     * @type {number}
     * @memberof StagePaginationResponse
     */
    total: number;
}

/**
 * Check if a given object implements the StagePaginationResponse interface.
 */
export function instanceOfStagePaginationResponse(value: object): value is StagePaginationResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function StagePaginationResponseFromJSON(json: any): StagePaginationResponse {
    return StagePaginationResponseFromJSONTyped(json, false);
}

export function StagePaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StagePaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StageResponseFromJSON)),
        'total': json['total'],
    };
}

  export function StagePaginationResponseToJSON(json: any): StagePaginationResponse {
      return StagePaginationResponseToJSONTyped(json, false);
  }

  export function StagePaginationResponseToJSONTyped(value?: StagePaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(StageResponseToJSON)),
        'total': value['total'],
    };
}

