/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateServiceSheetsRequest
 */
export interface UpdateServiceSheetsRequest {
    /**
     * Name of the serviceSheets
     * @type {string}
     * @memberof UpdateServiceSheetsRequest
     */
    workerId: string | null;
    /**
     * Speciality of the serviceSheets
     * @type {string}
     * @memberof UpdateServiceSheetsRequest
     */
    projectId: string | null;
    /**
     * Contact of the serviceSheets
     * @type {string}
     * @memberof UpdateServiceSheetsRequest
     */
    weekStartDate: string | null;
    /**
     * Email of the serviceSheets
     * @type {string}
     * @memberof UpdateServiceSheetsRequest
     */
    totalHours: string | null;
}

/**
 * Check if a given object implements the UpdateServiceSheetsRequest interface.
 */
export function instanceOfUpdateServiceSheetsRequest(value: object): value is UpdateServiceSheetsRequest {
    if (!('workerId' in value) || value['workerId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('weekStartDate' in value) || value['weekStartDate'] === undefined) return false;
    if (!('totalHours' in value) || value['totalHours'] === undefined) return false;
    return true;
}

export function UpdateServiceSheetsRequestFromJSON(json: any): UpdateServiceSheetsRequest {
    return UpdateServiceSheetsRequestFromJSONTyped(json, false);
}

export function UpdateServiceSheetsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateServiceSheetsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'workerId': json['workerId'],
        'projectId': json['projectId'],
        'weekStartDate': json['weekStartDate'],
        'totalHours': json['totalHours'],
    };
}

  export function UpdateServiceSheetsRequestToJSON(json: any): UpdateServiceSheetsRequest {
      return UpdateServiceSheetsRequestToJSONTyped(json, false);
  }

  export function UpdateServiceSheetsRequestToJSONTyped(value?: UpdateServiceSheetsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workerId': value['workerId'],
        'projectId': value['projectId'],
        'weekStartDate': value['weekStartDate'],
        'totalHours': value['totalHours'],
    };
}

