/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProjectQuotationRequest
 */
export interface UpdateProjectQuotationRequest {
    /**
     * Name of the projectQuotation
     * @type {string}
     * @memberof UpdateProjectQuotationRequest
     */
    projectId: string | null;
    /**
     * Material ID of the projectQuotation
     * @type {string}
     * @memberof UpdateProjectQuotationRequest
     */
    materialId: string | null;
    /**
     * Service ID of the projectQuotation
     * @type {string}
     * @memberof UpdateProjectQuotationRequest
     */
    serviceId: string | null;
    /**
     * Quantity of the projectQuotation
     * @type {number}
     * @memberof UpdateProjectQuotationRequest
     */
    quantity: number | null;
    /**
     * Total cost of the projectQuotation
     * @type {number}
     * @memberof UpdateProjectQuotationRequest
     */
    totalCost: number | null;
}

/**
 * Check if a given object implements the UpdateProjectQuotationRequest interface.
 */
export function instanceOfUpdateProjectQuotationRequest(value: object): value is UpdateProjectQuotationRequest {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('materialId' in value) || value['materialId'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('totalCost' in value) || value['totalCost'] === undefined) return false;
    return true;
}

export function UpdateProjectQuotationRequestFromJSON(json: any): UpdateProjectQuotationRequest {
    return UpdateProjectQuotationRequestFromJSONTyped(json, false);
}

export function UpdateProjectQuotationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProjectQuotationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'],
        'materialId': json['materialId'],
        'serviceId': json['serviceId'],
        'quantity': json['quantity'],
        'totalCost': json['totalCost'],
    };
}

  export function UpdateProjectQuotationRequestToJSON(json: any): UpdateProjectQuotationRequest {
      return UpdateProjectQuotationRequestToJSONTyped(json, false);
  }

  export function UpdateProjectQuotationRequestToJSONTyped(value?: UpdateProjectQuotationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
        'materialId': value['materialId'],
        'serviceId': value['serviceId'],
        'quantity': value['quantity'],
        'totalCost': value['totalCost'],
    };
}

