/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWorkerPaymentsRequest
 */
export interface UpdateWorkerPaymentsRequest {
    /**
     * Name of the workerPayments
     * @type {string}
     * @memberof UpdateWorkerPaymentsRequest
     */
    workerId?: string | null;
    /**
     * Speciality of the workerPayments
     * @type {string}
     * @memberof UpdateWorkerPaymentsRequest
     */
    serviceSheetId?: string | null;
    /**
     * Contact of the workerPayments
     * @type {number}
     * @memberof UpdateWorkerPaymentsRequest
     */
    totalPayment?: number | null;
    /**
     * Email of the workerPayments
     * @type {Date}
     * @memberof UpdateWorkerPaymentsRequest
     */
    paymentDate?: Date | null;
    /**
     * Is extra of the workerPayments
     * @type {boolean}
     * @memberof UpdateWorkerPaymentsRequest
     */
    isExtra?: boolean | null;
}

/**
 * Check if a given object implements the UpdateWorkerPaymentsRequest interface.
 */
export function instanceOfUpdateWorkerPaymentsRequest(value: object): value is UpdateWorkerPaymentsRequest {
    return true;
}

export function UpdateWorkerPaymentsRequestFromJSON(json: any): UpdateWorkerPaymentsRequest {
    return UpdateWorkerPaymentsRequestFromJSONTyped(json, false);
}

export function UpdateWorkerPaymentsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWorkerPaymentsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'workerId': json['workerId'] == null ? undefined : json['workerId'],
        'serviceSheetId': json['serviceSheetId'] == null ? undefined : json['serviceSheetId'],
        'totalPayment': json['totalPayment'] == null ? undefined : json['totalPayment'],
        'paymentDate': json['paymentDate'] == null ? undefined : (new Date(json['paymentDate'])),
        'isExtra': json['isExtra'] == null ? undefined : json['isExtra'],
    };
}

  export function UpdateWorkerPaymentsRequestToJSON(json: any): UpdateWorkerPaymentsRequest {
      return UpdateWorkerPaymentsRequestToJSONTyped(json, false);
  }

  export function UpdateWorkerPaymentsRequestToJSONTyped(value?: UpdateWorkerPaymentsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workerId': value['workerId'],
        'serviceSheetId': value['serviceSheetId'],
        'totalPayment': value['totalPayment'],
        'paymentDate': value['paymentDate'] == null ? undefined : ((value['paymentDate'] as any).toISOString()),
        'isExtra': value['isExtra'],
    };
}

