/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMaterialRequest
 */
export interface UpdateMaterialRequest {
    /**
     * Name of the material
     * @type {string}
     * @memberof UpdateMaterialRequest
     */
    name: string | null;
    /**
     * Unit cost of the material
     * @type {number}
     * @memberof UpdateMaterialRequest
     */
    unitCost: number | null;
}

/**
 * Check if a given object implements the UpdateMaterialRequest interface.
 */
export function instanceOfUpdateMaterialRequest(value: object): value is UpdateMaterialRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('unitCost' in value) || value['unitCost'] === undefined) return false;
    return true;
}

export function UpdateMaterialRequestFromJSON(json: any): UpdateMaterialRequest {
    return UpdateMaterialRequestFromJSONTyped(json, false);
}

export function UpdateMaterialRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMaterialRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'unitCost': json['unitCost'],
    };
}

  export function UpdateMaterialRequestToJSON(json: any): UpdateMaterialRequest {
      return UpdateMaterialRequestToJSONTyped(json, false);
  }

  export function UpdateMaterialRequestToJSONTyped(value?: UpdateMaterialRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'unitCost': value['unitCost'],
    };
}

