/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateInvoicesRequest
 */
export interface UpdateInvoicesRequest {
    /**
     * Stage id of invoices
     * @type {string}
     * @memberof UpdateInvoicesRequest
     */
    stageId?: string | null;
    /**
     * Invoice number of invoices
     * @type {string}
     * @memberof UpdateInvoicesRequest
     */
    invoiceNumber?: string | null;
    /**
     * Date of invoices
     * @type {string}
     * @memberof UpdateInvoicesRequest
     */
    date?: string | null;
    /**
     * Total amount of invoices
     * @type {number}
     * @memberof UpdateInvoicesRequest
     */
    totalAmount?: number | null;
    /**
     * Show materials of invoices
     * @type {boolean}
     * @memberof UpdateInvoicesRequest
     */
    showMaterials?: boolean | null;
}

/**
 * Check if a given object implements the UpdateInvoicesRequest interface.
 */
export function instanceOfUpdateInvoicesRequest(value: object): value is UpdateInvoicesRequest {
    return true;
}

export function UpdateInvoicesRequestFromJSON(json: any): UpdateInvoicesRequest {
    return UpdateInvoicesRequestFromJSONTyped(json, false);
}

export function UpdateInvoicesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateInvoicesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'stageId': json['stageId'] == null ? undefined : json['stageId'],
        'invoiceNumber': json['invoiceNumber'] == null ? undefined : json['invoiceNumber'],
        'date': json['date'] == null ? undefined : json['date'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'showMaterials': json['showMaterials'] == null ? undefined : json['showMaterials'],
    };
}

  export function UpdateInvoicesRequestToJSON(json: any): UpdateInvoicesRequest {
      return UpdateInvoicesRequestToJSONTyped(json, false);
  }

  export function UpdateInvoicesRequestToJSONTyped(value?: UpdateInvoicesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stageId': value['stageId'],
        'invoiceNumber': value['invoiceNumber'],
        'date': value['date'],
        'totalAmount': value['totalAmount'],
        'showMaterials': value['showMaterials'],
    };
}

