/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateStageRequest
 */
export interface UpdateStageRequest {
    /**
     * Name of the stage
     * @type {string}
     * @memberof UpdateStageRequest
     */
    name?: string | null;
    /**
     * Description of the stage
     * @type {string}
     * @memberof UpdateStageRequest
     */
    description?: string | null;
    /**
     * Project ID of the stage
     * @type {string}
     * @memberof UpdateStageRequest
     */
    projectId?: string | null;
    /**
     * Percentage of the stage
     * @type {number}
     * @memberof UpdateStageRequest
     */
    percentage?: number | null;
    /**
     * Adjusted percentage of the stage
     * @type {number}
     * @memberof UpdateStageRequest
     */
    adjustedPercentage?: number | null;
    /**
     * Start date of the stage
     * @type {Date}
     * @memberof UpdateStageRequest
     */
    startDate?: Date | null;
    /**
     * End date of the stage
     * @type {Date}
     * @memberof UpdateStageRequest
     */
    endDate?: Date | null;
}

/**
 * Check if a given object implements the UpdateStageRequest interface.
 */
export function instanceOfUpdateStageRequest(value: object): value is UpdateStageRequest {
    return true;
}

export function UpdateStageRequestFromJSON(json: any): UpdateStageRequest {
    return UpdateStageRequestFromJSONTyped(json, false);
}

export function UpdateStageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateStageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
        'adjustedPercentage': json['adjustedPercentage'] == null ? undefined : json['adjustedPercentage'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
    };
}

  export function UpdateStageRequestToJSON(json: any): UpdateStageRequest {
      return UpdateStageRequestToJSONTyped(json, false);
  }

  export function UpdateStageRequestToJSONTyped(value?: UpdateStageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'projectId': value['projectId'],
        'percentage': value['percentage'],
        'adjustedPercentage': value['adjustedPercentage'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
    };
}

