/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWorkerAssignmentRequest
 */
export interface UpdateWorkerAssignmentRequest {
    /**
     * Name of the workerAssignment
     * @type {string}
     * @memberof UpdateWorkerAssignmentRequest
     */
    workerId: string | null;
    /**
     * Project ID of the workerAssignment
     * @type {string}
     * @memberof UpdateWorkerAssignmentRequest
     */
    projectId: string | null;
    /**
     * Stage ID of the workerAssignment
     * @type {string}
     * @memberof UpdateWorkerAssignmentRequest
     */
    stageId: string | null;
}

/**
 * Check if a given object implements the UpdateWorkerAssignmentRequest interface.
 */
export function instanceOfUpdateWorkerAssignmentRequest(value: object): value is UpdateWorkerAssignmentRequest {
    if (!('workerId' in value) || value['workerId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('stageId' in value) || value['stageId'] === undefined) return false;
    return true;
}

export function UpdateWorkerAssignmentRequestFromJSON(json: any): UpdateWorkerAssignmentRequest {
    return UpdateWorkerAssignmentRequestFromJSONTyped(json, false);
}

export function UpdateWorkerAssignmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWorkerAssignmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'workerId': json['workerId'],
        'projectId': json['projectId'],
        'stageId': json['stageId'],
    };
}

  export function UpdateWorkerAssignmentRequestToJSON(json: any): UpdateWorkerAssignmentRequest {
      return UpdateWorkerAssignmentRequestToJSONTyped(json, false);
  }

  export function UpdateWorkerAssignmentRequestToJSONTyped(value?: UpdateWorkerAssignmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workerId': value['workerId'],
        'projectId': value['projectId'],
        'stageId': value['stageId'],
    };
}

