/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProjectRequest
 */
export interface UpdateProjectRequest {
    /**
     * Client id of the project
     * @type {string}
     * @memberof UpdateProjectRequest
     */
    clientId?: string | null;
    /**
     * Name of the project
     * @type {string}
     * @memberof UpdateProjectRequest
     */
    name?: string | null;
    /**
     * Description of the project
     * @type {string}
     * @memberof UpdateProjectRequest
     */
    description?: string | null;
    /**
     * Location of the project
     * @type {string}
     * @memberof UpdateProjectRequest
     */
    location?: string | null;
    /**
     * Start date of the project
     * @type {Date}
     * @memberof UpdateProjectRequest
     */
    startDate?: Date | null;
    /**
     * End date of the project
     * @type {Date}
     * @memberof UpdateProjectRequest
     */
    endDate?: Date | null;
}

/**
 * Check if a given object implements the UpdateProjectRequest interface.
 */
export function instanceOfUpdateProjectRequest(value: object): value is UpdateProjectRequest {
    return true;
}

export function UpdateProjectRequestFromJSON(json: any): UpdateProjectRequest {
    return UpdateProjectRequestFromJSONTyped(json, false);
}

export function UpdateProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : json['location'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
    };
}

  export function UpdateProjectRequestToJSON(json: any): UpdateProjectRequest {
      return UpdateProjectRequestToJSONTyped(json, false);
  }

  export function UpdateProjectRequestToJSONTyped(value?: UpdateProjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientId': value['clientId'],
        'name': value['name'],
        'description': value['description'],
        'location': value['location'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
    };
}

