/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateServiceRequest
 */
export interface UpdateServiceRequest {
    /**
     * Name of the service
     * @type {string}
     * @memberof UpdateServiceRequest
     */
    name: string | null;
    /**
     * Description of the service
     * @type {string}
     * @memberof UpdateServiceRequest
     */
    description: string | null;
    /**
     * Project ID of the service
     * @type {string}
     * @memberof UpdateServiceRequest
     */
    unitCost: string | null;
}

/**
 * Check if a given object implements the UpdateServiceRequest interface.
 */
export function instanceOfUpdateServiceRequest(value: object): value is UpdateServiceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('unitCost' in value) || value['unitCost'] === undefined) return false;
    return true;
}

export function UpdateServiceRequestFromJSON(json: any): UpdateServiceRequest {
    return UpdateServiceRequestFromJSONTyped(json, false);
}

export function UpdateServiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateServiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'unitCost': json['unitCost'],
    };
}

  export function UpdateServiceRequestToJSON(json: any): UpdateServiceRequest {
      return UpdateServiceRequestToJSONTyped(json, false);
  }

  export function UpdateServiceRequestToJSONTyped(value?: UpdateServiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'unitCost': value['unitCost'],
    };
}

