/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';

/**
 * 
 * @export
 * @interface UserPaginationResponse
 */
export interface UserPaginationResponse {
    /**
     * Data of the user
     * @type {Array<UserResponse>}
     * @memberof UserPaginationResponse
     */
    data: Array<UserResponse>;
    /**
     * Total of the user
     * @type {number}
     * @memberof UserPaginationResponse
     */
    total: number;
}

/**
 * Check if a given object implements the UserPaginationResponse interface.
 */
export function instanceOfUserPaginationResponse(value: object): value is UserPaginationResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function UserPaginationResponseFromJSON(json: any): UserPaginationResponse {
    return UserPaginationResponseFromJSONTyped(json, false);
}

export function UserPaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UserResponseFromJSON)),
        'total': json['total'],
    };
}

  export function UserPaginationResponseToJSON(json: any): UserPaginationResponse {
      return UserPaginationResponseToJSONTyped(json, false);
  }

  export function UserPaginationResponseToJSONTyped(value?: UserPaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(UserResponseToJSON)),
        'total': value['total'],
    };
}

