/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkerAssignmentResponse } from './WorkerAssignmentResponse';
import {
    WorkerAssignmentResponseFromJSON,
    WorkerAssignmentResponseFromJSONTyped,
    WorkerAssignmentResponseToJSON,
    WorkerAssignmentResponseToJSONTyped,
} from './WorkerAssignmentResponse';

/**
 * 
 * @export
 * @interface WorkerAssignmentPaginationResponse
 */
export interface WorkerAssignmentPaginationResponse {
    /**
     * Data of the workerAssignment
     * @type {Array<WorkerAssignmentResponse>}
     * @memberof WorkerAssignmentPaginationResponse
     */
    data: Array<WorkerAssignmentResponse>;
    /**
     * Total of the workerAssignment
     * @type {number}
     * @memberof WorkerAssignmentPaginationResponse
     */
    total: number;
}

/**
 * Check if a given object implements the WorkerAssignmentPaginationResponse interface.
 */
export function instanceOfWorkerAssignmentPaginationResponse(value: object): value is WorkerAssignmentPaginationResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function WorkerAssignmentPaginationResponseFromJSON(json: any): WorkerAssignmentPaginationResponse {
    return WorkerAssignmentPaginationResponseFromJSONTyped(json, false);
}

export function WorkerAssignmentPaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkerAssignmentPaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(WorkerAssignmentResponseFromJSON)),
        'total': json['total'],
    };
}

  export function WorkerAssignmentPaginationResponseToJSON(json: any): WorkerAssignmentPaginationResponse {
      return WorkerAssignmentPaginationResponseToJSONTyped(json, false);
  }

  export function WorkerAssignmentPaginationResponseToJSONTyped(value?: WorkerAssignmentPaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(WorkerAssignmentResponseToJSON)),
        'total': value['total'],
    };
}

