/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkerPaymentsResponse } from './WorkerPaymentsResponse';
import {
    WorkerPaymentsResponseFromJSON,
    WorkerPaymentsResponseFromJSONTyped,
    WorkerPaymentsResponseToJSON,
    WorkerPaymentsResponseToJSONTyped,
} from './WorkerPaymentsResponse';

/**
 * 
 * @export
 * @interface WorkerPaymentsPaginationResponse
 */
export interface WorkerPaymentsPaginationResponse {
    /**
     * Data of the workerPayments
     * @type {Array<WorkerPaymentsResponse>}
     * @memberof WorkerPaymentsPaginationResponse
     */
    data: Array<WorkerPaymentsResponse>;
    /**
     * Total of the workerPayments
     * @type {number}
     * @memberof WorkerPaymentsPaginationResponse
     */
    total: number;
}

/**
 * Check if a given object implements the WorkerPaymentsPaginationResponse interface.
 */
export function instanceOfWorkerPaymentsPaginationResponse(value: object): value is WorkerPaymentsPaginationResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function WorkerPaymentsPaginationResponseFromJSON(json: any): WorkerPaymentsPaginationResponse {
    return WorkerPaymentsPaginationResponseFromJSONTyped(json, false);
}

export function WorkerPaymentsPaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkerPaymentsPaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(WorkerPaymentsResponseFromJSON)),
        'total': json['total'],
    };
}

  export function WorkerPaymentsPaginationResponseToJSON(json: any): WorkerPaymentsPaginationResponse {
      return WorkerPaymentsPaginationResponseToJSONTyped(json, false);
  }

  export function WorkerPaymentsPaginationResponseToJSONTyped(value?: WorkerPaymentsPaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(WorkerPaymentsResponseToJSON)),
        'total': value['total'],
    };
}

