/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkerResponse } from './WorkerResponse';
import {
    WorkerResponseFromJSON,
    WorkerResponseFromJSONTyped,
    WorkerResponseToJSON,
    WorkerResponseToJSONTyped,
} from './WorkerResponse';

/**
 * 
 * @export
 * @interface WorkerPaginationResponse
 */
export interface WorkerPaginationResponse {
    /**
     * Data of the worker
     * @type {Array<WorkerResponse>}
     * @memberof WorkerPaginationResponse
     */
    data: Array<WorkerResponse>;
    /**
     * Total of the worker
     * @type {number}
     * @memberof WorkerPaginationResponse
     */
    total: number;
}

/**
 * Check if a given object implements the WorkerPaginationResponse interface.
 */
export function instanceOfWorkerPaginationResponse(value: object): value is WorkerPaginationResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function WorkerPaginationResponseFromJSON(json: any): WorkerPaginationResponse {
    return WorkerPaginationResponseFromJSONTyped(json, false);
}

export function WorkerPaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkerPaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(WorkerResponseFromJSON)),
        'total': json['total'],
    };
}

  export function WorkerPaginationResponseToJSON(json: any): WorkerPaginationResponse {
      return WorkerPaginationResponseToJSONTyped(json, false);
  }

  export function WorkerPaginationResponseToJSONTyped(value?: WorkerPaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(WorkerResponseToJSON)),
        'total': value['total'],
    };
}

