/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkerAssignmentResponse
 */
export interface WorkerAssignmentResponse {
    /**
     * Id of the workerAssignment
     * @type {string}
     * @memberof WorkerAssignmentResponse
     */
    id: string;
    /**
     * Name of the workerAssignment
     * @type {string}
     * @memberof WorkerAssignmentResponse
     */
    workerId: string | null;
    /**
     * Project ID of the workerAssignment
     * @type {string}
     * @memberof WorkerAssignmentResponse
     */
    projectId: string | null;
    /**
     * Stage ID of the workerAssignment
     * @type {string}
     * @memberof WorkerAssignmentResponse
     */
    stageId: string | null;
    /**
     * Created at of the workerAssignment
     * @type {string}
     * @memberof WorkerAssignmentResponse
     */
    createdAt: string | null;
    /**
     * Updated at of the workerAssignment
     * @type {string}
     * @memberof WorkerAssignmentResponse
     */
    updatedAt: string | null;
}

/**
 * Check if a given object implements the WorkerAssignmentResponse interface.
 */
export function instanceOfWorkerAssignmentResponse(value: object): value is WorkerAssignmentResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('workerId' in value) || value['workerId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('stageId' in value) || value['stageId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function WorkerAssignmentResponseFromJSON(json: any): WorkerAssignmentResponse {
    return WorkerAssignmentResponseFromJSONTyped(json, false);
}

export function WorkerAssignmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkerAssignmentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'workerId': json['workerId'],
        'projectId': json['projectId'],
        'stageId': json['stageId'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

  export function WorkerAssignmentResponseToJSON(json: any): WorkerAssignmentResponse {
      return WorkerAssignmentResponseToJSONTyped(json, false);
  }

  export function WorkerAssignmentResponseToJSONTyped(value?: WorkerAssignmentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workerId': value['workerId'],
        'projectId': value['projectId'],
        'stageId': value['stageId'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

