/* tslint:disable */
/* eslint-disable */
/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkerRatesResponse
 */
export interface WorkerRatesResponse {
    /**
     * Id of the workerRates
     * @type {string}
     * @memberof WorkerRatesResponse
     */
    id: string;
    /**
     * Rate of the workerRates
     * @type {number}
     * @memberof WorkerRatesResponse
     */
    rate: number | null;
    /**
     * Effective date of the workerRates
     * @type {Date}
     * @memberof WorkerRatesResponse
     */
    effectiveDate: Date | null;
    /**
     * Created at of the workerRates
     * @type {Date}
     * @memberof WorkerRatesResponse
     */
    createdAt: Date | null;
    /**
     * Updated at of the workerRates
     * @type {Date}
     * @memberof WorkerRatesResponse
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the WorkerRatesResponse interface.
 */
export function instanceOfWorkerRatesResponse(value: object): value is WorkerRatesResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('rate' in value) || value['rate'] === undefined) return false;
    if (!('effectiveDate' in value) || value['effectiveDate'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function WorkerRatesResponseFromJSON(json: any): WorkerRatesResponse {
    return WorkerRatesResponseFromJSONTyped(json, false);
}

export function WorkerRatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkerRatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'rate': json['rate'],
        'effectiveDate': (json['effectiveDate'] == null ? null : new Date(json['effectiveDate'])),
        'createdAt': (json['createdAt'] == null ? null : new Date(json['createdAt'])),
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
    };
}

  export function WorkerRatesResponseToJSON(json: any): WorkerRatesResponse {
      return WorkerRatesResponseToJSONTyped(json, false);
  }

  export function WorkerRatesResponseToJSONTyped(value?: WorkerRatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'rate': value['rate'],
        'effectiveDate': (value['effectiveDate'] == null ? null : (value['effectiveDate'] as any).toISOString()),
        'createdAt': (value['createdAt'] == null ? null : (value['createdAt'] as any).toISOString()),
        'updatedAt': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
    };
}

