/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateInvoicesRequest {
    /**
    * Stage id of invoices
    */
    'stageId': string | null;
    /**
    * Invoice number of invoices
    */
    'invoiceNumber': string | null;
    /**
    * Date of invoices
    */
    'date': string | null;
    /**
    * Total amount of invoices
    */
    'totalAmount': number | null;
    /**
    * Show materials of invoices
    */
    'showMaterials': boolean | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "stageId",
            "baseName": "stageId",
            "type": "string"
        },
        {
            "name": "invoiceNumber",
            "baseName": "invoiceNumber",
            "type": "string"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "totalAmount",
            "baseName": "totalAmount",
            "type": "number"
        },
        {
            "name": "showMaterials",
            "baseName": "showMaterials",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CreateInvoicesRequest.attributeTypeMap;
    }
}

