/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateWorkerRatesRequest {
    /**
    * Name of the workerRates
    */
    'workerId': string | null;
    /**
    * Rate of the workerRates
    */
    'rate': number | null;
    /**
    * Effective date of the workerRates
    */
    'effectiveDate': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "workerId",
            "baseName": "workerId",
            "type": "string"
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "number"
        },
        {
            "name": "effectiveDate",
            "baseName": "effectiveDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateWorkerRatesRequest.attributeTypeMap;
    }
}

