/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InvoicesResponse {
    /**
    * Id of the invoices
    */
    'id': string;
    /**
    * Stage id of invoices
    */
    'stageId': string | null;
    /**
    * Invoice number of invoices
    */
    'invoiceNumber': string | null;
    /**
    * Date of invoices
    */
    'date': string | null;
    /**
    * Total amount of invoices
    */
    'totalAmount': number | null;
    /**
    * Show materials of invoices
    */
    'showMaterials': boolean | null;
    /**
    * Created at of the invoices
    */
    'createdAt': string | null;
    /**
    * Updated at of the invoices
    */
    'updatedAt': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "stageId",
            "baseName": "stageId",
            "type": "string"
        },
        {
            "name": "invoiceNumber",
            "baseName": "invoiceNumber",
            "type": "string"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "totalAmount",
            "baseName": "totalAmount",
            "type": "number"
        },
        {
            "name": "showMaterials",
            "baseName": "showMaterials",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InvoicesResponse.attributeTypeMap;
    }
}

