/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProjectQuotationResponse {
    /**
    * Name of the projectQuotation
    */
    'projectId': string | null;
    /**
    * Material ID of the projectQuotation
    */
    'materialId': string | null;
    /**
    * Service ID of the projectQuotation
    */
    'serviceId': string | null;
    /**
    * Quantity of the projectQuotation
    */
    'quantity': number | null;
    /**
    * Total cost of the projectQuotation
    */
    'totalCost': number | null;
    /**
    * ID of the projectQuotation
    */
    'id': string;
    /**
    * Created at of the projectQuotation
    */
    'createdAt': Date | null;
    /**
    * Updated at of the projectQuotation
    */
    'updatedAt': Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "string"
        },
        {
            "name": "materialId",
            "baseName": "materialId",
            "type": "string"
        },
        {
            "name": "serviceId",
            "baseName": "serviceId",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "totalCost",
            "baseName": "totalCost",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return ProjectQuotationResponse.attributeTypeMap;
    }
}

