/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ServiceSheetsResponse {
    /**
    * Id of the serviceSheets
    */
    'id': string;
    /**
    * Name of the serviceSheets
    */
    'workerId': string | null;
    /**
    * Speciality of the serviceSheets
    */
    'projectId': string | null;
    /**
    * Contact of the serviceSheets
    */
    'weekStartDate': string | null;
    /**
    * Email of the serviceSheets
    */
    'totalHours': string | null;
    /**
    * Created at of the serviceSheets
    */
    'createdAt': string | null;
    /**
    * Updated at of the serviceSheets
    */
    'updatedAt': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "workerId",
            "baseName": "workerId",
            "type": "string"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "string"
        },
        {
            "name": "weekStartDate",
            "baseName": "weekStartDate",
            "type": "string"
        },
        {
            "name": "totalHours",
            "baseName": "totalHours",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ServiceSheetsResponse.attributeTypeMap;
    }
}

