/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class StageResponse {
    /**
    * Id of the stage
    */
    'id': string;
    /**
    * Name of the stage
    */
    'name': string | null;
    /**
    * Description of the stage
    */
    'description': string | null;
    /**
    * Project ID of the stage
    */
    'projectId': string | null;
    /**
    * Percentage of the stage
    */
    'percentage': number | null;
    /**
    * Adjusted percentage of the stage
    */
    'adjustedPercentage': Date | null;
    /**
    * Start date of the stage
    */
    'startDate': Date | null;
    /**
    * End date of the stage
    */
    'endDate': string | null;
    /**
    * Created at of the stage
    */
    'createdAt': string | null;
    /**
    * Updated at of the stage
    */
    'updatedAt': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "string"
        },
        {
            "name": "percentage",
            "baseName": "percentage",
            "type": "number"
        },
        {
            "name": "adjustedPercentage",
            "baseName": "adjustedPercentage",
            "type": "Date"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StageResponse.attributeTypeMap;
    }
}

