/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateServiceRequest {
    /**
    * Name of the service
    */
    'name': string | null;
    /**
    * Description of the service
    */
    'description': string | null;
    /**
    * Project ID of the service
    */
    'unitCost': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "unitCost",
            "baseName": "unitCost",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateServiceRequest.attributeTypeMap;
    }
}

