/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class VersionResponse {
    /**
    * Commit version
    */
    'commitVersion': string;
    /**
    * Commit date
    */
    'commitDate': string;
    /**
    * Api version
    */
    'apiVersion': string;
    /**
    * Date version
    */
    'dateVersion': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commitVersion",
            "baseName": "commitVersion",
            "type": "string"
        },
        {
            "name": "commitDate",
            "baseName": "commitDate",
            "type": "string"
        },
        {
            "name": "apiVersion",
            "baseName": "apiVersion",
            "type": "string"
        },
        {
            "name": "dateVersion",
            "baseName": "dateVersion",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return VersionResponse.attributeTypeMap;
    }
}

