/**
 * Smart Power Electric API
 * Smart Power Electric API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WorkerPaymentsResponse {
    /**
    * Id of the workerPayments
    */
    'id': string;
    /**
    * Name of the workerPayments
    */
    'workerId': string | null;
    /**
    * Speciality of the workerPayments
    */
    'serviceSheetId': string | null;
    /**
    * Contact of the workerPayments
    */
    'totalPayment': string | null;
    /**
    * Email of the workerPayments
    */
    'paymentDate': string | null;
    /**
    * Is extra of the workerPayments
    */
    'isExtra': string | null;
    /**
    * Created at of the workerPayments
    */
    'createdAt': string | null;
    /**
    * Updated at of the workerPayments
    */
    'updatedAt': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "workerId",
            "baseName": "workerId",
            "type": "string"
        },
        {
            "name": "serviceSheetId",
            "baseName": "serviceSheetId",
            "type": "string"
        },
        {
            "name": "totalPayment",
            "baseName": "totalPayment",
            "type": "string"
        },
        {
            "name": "paymentDate",
            "baseName": "paymentDate",
            "type": "string"
        },
        {
            "name": "isExtra",
            "baseName": "isExtra",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WorkerPaymentsResponse.attributeTypeMap;
    }
}

